### ISSUE TITLE
Directory creation fails because it contains slashes 

### ISSUE THREAD

**Issue by aboueleyes** [AbdullahKady/met-downloader#17]
Opening the course page(node:10982) UnhandledPromiseRejectionWarning: Error: ENOENT: no such file or directory, mkdir '/home/ibrahim/CSEN 301 Data Structures and Algorithms/1-Arrays/Sorting/Stacks I'
    at Object.mkdirSync (fs.js:757:3)
    at downloadMaterial (/usr/local/lib/node_modules/met-downloader/src/app.js:60:8)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:10982) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:10982) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by aboueleyes** [comment]
This problem occurred while downloading CS3 course , other courses worked fine

**Comment by AbdullahKady** [comment]
Hi @aboueleyes Thanks for filing the issue! If you happen to fix it anytime, please feel free to open a PR.
I'm not actively maintaining most of my university projects -unfortunately-, but If I have the time, I'll try to look into it.

**Comment by aboueleyes** [comment]
Thanks @AbdullahKady  :)
